# Generated by Django 5.2.4 on 2025-07-22 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("ano_lancamento", models.IntegerField(blank=True, null=True)),
                (
                    "capa_album",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albuns",
                        to="player.artista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "compositor",
                    models.CharField(default="Não informado", max_length=200),
                ),
                ("genero", models.CharField(default="Não informado", max_length=50)),
                ("duracao", models.DurationField(default=datetime.timedelta(0))),
                ("letra", models.TextField(blank=True)),
                ("arquivo_audio", models.FileField(upload_to="audio_files/")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musicas",
                        to="player.album",
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musicas",
                        to="player.artista",
                    ),
                ),
            ],
        ),
    ]
