# Generated by Django 5.2.4 on 2025-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_alter_musica_letra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="letra",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
